config/routes.rb
Rails.application.routes.draw do
  resources :venuecategories
  resources :categories
  root to: "home#index"
  resources :favorites
  resources :ratings
  resources :comments
  resources :posts
  resources :profile
  get '/venues/map_all' => 'venues#map_all', as: :venue_map_all
  get '/venues(/type/:page)' => 'venues#index', as: :venues_page
  resources :venues
  get 'categories/:category_id/venues' => 'venues#category_feed', as: :venue_category_feed
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  get '/map' => 'map#index'  
  post '/posts/:id'=> 'posts#update', as: :post_id
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'venues/:venue_id/star/:rating' => 'ratings#update', as: :venue_rating
  get 'showvenue' => 'venues#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :venue_categories
	has_many :venues, :through => :venue_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :venue
  belongs_to :location, required: false
  belongs_to :post, required: false
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :venue
  mount_uploader :image, ImageUploader
  has_many :comments
  has_many :favorites
  has_many :ratings
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :venue, required: false
  belongs_to :post, required: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_many :ratings
  has_many :favorites
  has_many :venues, :through => :favorites
  has_many :posts
  has_many :comments
end

app/models/venue.rb
class Venue < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :venue_categories
	has_many :categories, :through => :venue_categories
	has_many :ratings
	has_many :favorites
	has_many :users , :through => :favorites
	has_many :posts

	def mean_rating
    self.ratings.average(:rating).to_f
  end
  geocoded_by :address
	after_validation :geocode
end

app/models/venue_category.rb
class VenueCategory < ApplicationRecord
  belongs_to :venue
  belongs_to :category
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@homepage = true
    @favorites = current_user ? current_user.favorites : Favorite.where(nil)
		@posts = Post.order('created_at DESC').limit(10)
		@venues = Venue.all
	end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
	def index
		@venues = Venue.all
  end
  
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    unless user_signed_in? && current_user.admin?
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
    unless user_signed_in? && current_user.admin?
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    @rating = Rating.find_by(user_id: current_user.id, bar_id: params[:bar_id]) || Rating.new
    @rating.user_id = current_user.id
    @rating.bar_id =  params[:bar_id]
    @rating.rating = params[:rating]

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.js 
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:bar_id, :user_id, :rating, :user_id, :bar_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ratings/_form.html.erb
<%= form_with(model: rating, local: true) do |form| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location_id %>
    <%= form.number_field :location_id, id: :rating_location_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :rating_user_id %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id, id: :rating_post_id %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :rating_rating %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :rating_user_id %>
  </div>

  <div class="field">
    <%= form.label :location_id %>
    <%= form.text_field :location_id, id: :rating_location_id %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id, id: :rating_post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>User</th>
      <th>Post</th>
      <th>Rating</th>
      <th>User</th>
      <th>Location</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.location_id %></td>
        <td><%= rating.user_id %></td>
        <td><%= rating.post_id %></td>
        <td><%= rating.rating %></td>
        <td><%= rating.user %></td>
        <td><%= rating.location %></td>
        <td><%= rating.post %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @rating.location_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @rating.post_id %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @rating.rating %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user %>
</p>

<p>
  <strong>Location:</strong>
  <%= @rating.location %>
</p>

<p>
  <strong>Post:</strong>
  <%= @rating.post %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>