config/routes.rb
Rails.application.routes.draw do
  resources :venuecategories
  resources :categories
  root to: "home#index"
  resources :favorites
  resources :ratings
  resources :comments
  resources :posts
  resources :profile
  get '/venues/map_all' => 'venues#map_all', as: :venue_map_all
  get '/venues(/type/:page)' => 'venues#index', as: :venues_page
  resources :venues
  get 'categories/:category_id/venues' => 'venues#category_feed', as: :venue_category_feed
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  get '/map' => 'map#index'  
  post '/posts/:id'=> 'posts#update', as: :post_id
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'venues/:venue_id/star/:rating' => 'ratings#update', as: :venue_rating
  get 'showvenue' => 'venues#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :venue_categories
	has_many :venues, :through => :venue_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :venue
  belongs_to :location, required: false
  belongs_to :post, required: false
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :venue
  mount_uploader :image, ImageUploader
  has_many :comments
  has_many :favorites
  has_many :ratings
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :venue, required: false
  belongs_to :post, required: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_many :ratings
  has_many :favorites
  has_many :venues, :through => :favorites
  has_many :posts
  has_many :comments
end

app/models/venue.rb
class Venue < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :venue_categories
	has_many :categories, :through => :venue_categories
	has_many :ratings
	has_many :favorites
	has_many :users , :through => :favorites
	has_many :posts

	def mean_rating
    self.ratings.average(:rating).to_f
  end
  geocoded_by :address
	after_validation :geocode
end

app/models/venue_category.rb
class VenueCategory < ApplicationRecord
  belongs_to :venue
  belongs_to :category
end

app/controllers/map_controller.rb
class MapController < ApplicationController
	def index
		@venues = Venue.all
  end
  
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  def index
    @venues = VenueCategory.where(category_id: 4).map{|vc| vc.venue}
    @ratings = Rating.all
    @favorites = Favorite.all
    @posts = Post.all
  end

  def category_feed
    @venues = VenueCategory.where(category_id: params[:category_id]).map{|vc| vc.venue}
    respond_to do |format|
      format.json { render :index, status: :ok, venues: @venues }
    end
  end

  def map_all
    @venues = Venue.all
    respond_to do |format|
      format.json { render :index, status: :ok, venues: @venues }
    end
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
    @posts = Post.all
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @rating = Rating.new(rating_params)
    @venue = Venue.new(venue_params)   
    Venue.transaction do
      @venue.save
      @rating.user_id = current_user.id
      @rating.save
    end

    respond_to do |format|
      if @venue.save && @rating.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, venue: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, venue: @venue }
      else
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name, :bio, :address, :phone, :image, :favorite_id, :google_rating, :yelp_rating, :venue_id)
    end
    def rating_params
      params.require(:venue).permit(:venue_id, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/venues/_createform.html.erb
<div class="createvenue" class="row">
	<div id="close3">x</div>
	<%= form_with(model: @venue, local: true) do |form| %>
	  <% if @venue.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

	      <ul>
	      <% @venue.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  <div class="row">
	  	<h3>New Venue</h3>
	  </div>
	  <div class="field row">
	    <%= form.label :name %>
	    <%= form.text_field :name, id: "placename"%>
	  </div>

	  <div class="field row">
	    <%= form.label :bio %>
	    <%= form.text_area :bio, id: :venue_bio %>
	  </div>

	  <div class="field row">
	    <%= form.label :address %>
	    <%= form.text_field :address, id: "placeaddress" %>
	  </div>

	  <div class="field row">
	    <%= form.label :phone %>
	    <%= form.text_field :phone, id: "placephone" %>
	  </div>

	  <div class="field row">
	    <%= form.label "Our Rating" %>
	    <%= form.number_field :rating, :step => "0.01", id: :rating %>
	  </div>

	  <div class="field row">
	    <%= form.label :google_rating %>
	    <%= form.number_field :google_rating, :step => "0.01", id: "placerating" %>
	  </div>

	   <div class="field row">
	    <%= form.label :yelp_rating %>
	    <%= form.number_field :yelp_rating, :step => "0.01" %>
	  </div>

	  <div class="row">
	  	<%= form.label "Image: " %>
	    <%= form.file_field :image, id: "image" %>
	  </div>

	  <div class="row">
	  	<%= form.label "Hours " %>
	    <%= form.text_field :hrs, id: "placehrs" %>
	  </div>

	  <div class="field row">
	  	<div class="col-md-4 checklist">
	  		<div class="row">
	  			<h4>Bars</h4>
	  		</div>
	  		<div class="row">
	  			<%= form.label :music %>
	  			<%= form.check_box :category, {:multiple => true}, "music", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :dancing %>
	  			<%= form.check_box :category, {:multiple => true}, "dancing", nil %>
	  		</div>
	  		<div class="row">
	  		<%= form.label :rooftop %>
	  			<%= form.check_box :category, {:multiple => true}, "rooftop", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :relaxed %>
	  			<%= form.check_box :category, {:multiple => true}, "relaxed", nil %>
	  		</div>
	  	</div>
	  	<div class="col-md-4 border checklist">
	  		<div class="row">
	  			<h4>Restaurants</h4>
	  		</div>
	  		<div class="row">
	  			<%= form.label "Suit & Tie" %>
	  			<%= form.check_box :category, {:multiple => true}, "Suit & Tie", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label "Classy & Casual" %>
	  			<%= form.check_box :category, {:multiple => true}, "Classy & Casual", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label "Hipster & Biergartens" %>
	  			<%= form.check_box :category, {:multiple => true}, "Hipster & Biergartens", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :Quick_Bite %>
	  			<%= form.check_box :category, {:multiple => true}, "Quick Bite", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :Vegan %>
	  			<%= form.check_box :category, {:multiple => true}, "Vegan/Vegetarian", nil %>
	  		</div>
	  	</div>
	  	<div class="col-md-4 checklist">
	  		<div class="row">
	  			<h4>Activites</h4>
	  		</div>
	  		<div class="row">
	  			<%= form.label :athletic %>
	  			<%= form.check_box :category, {:multiple => true}, "Athletic", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :Relaxed_Fun %>
	  			<%= form.check_box :category, {:multiple => true}, "Relaxed Fun", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :Day_Trip %>
	  			<%= form.check_box :category, {:multiple => true}, "Day Trip", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :Free %>
	  			<%= form.check_box :category, {:multiple => true}, "Free", nil %>
	  		</div>
	  	</div>
	  </div>

	  <div class="actions row">
	    <%= form.submit %>
	  </div>
	<% end %>
</div>

app/views/venues/_editform.html.erb
<div class="editvenue" class="row">
	<div id="close4">x</div>
	<%= form_with(model: @venue, local: true) do |form| %>
	  <% if @venue.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

	      <ul>
	      <% @venue.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  <div class="row">
	  	<h3>Edit Venue</h3>
	  </div>
	  <div class="field row">
	    <%= form.label :name %>
	    <%= form.text_field :name, id: "editname"%>
	  </div>

	  <div class="field row">
	    <%= form.label :bio %>
	    <%= form.text_area :bio, id: :venue_bio %>
	  </div>

	  <div class="field row">
	    <%= form.label :address %>
	    <%= form.text_field :address, id: "editaddress" %>
	  </div>

	  <div class="field row">
	    <%= form.label :phone %>
	    <%= form.text_field :phone, id: "editphone" %>
	  </div>

	  <div class="field row">
	    <%= form.label "Our Rating" %>
	    <%= form.number_field :rating_id, :step => "0.01", id:  "editrating"%>
	  </div>

	  <div class="field row">
	    <%= form.label :google_rating %>
	    <%= form.number_field :google_rating, :step => "0.01" %>
	  </div>

	   <div class="field row">
	    <%= form.label :yelp_rating %>
	    <%= form.number_field :yelp_rating, :step => "0.01" %>
	  </div>

	  <div class="row">
	  	<%= form.label "Image: " %>
	    <%= form.file_field :image, id: "image", :class => "editimage" %>
	  </div>

	  <div class="row">
	  	<%= form.label "Hours " %>
	    <%= form.text_field :hrs, id: "edithrs"%>
	  </div>

	  <div class="field row">
	  	<div class="col-md-4 checklist">
	  		<div class="row">
	  			<h4>Bars</h4>
	  		</div>
	  		<div class="row">
	  			<%= form.label :music %>
	  			<%= form.check_box :category, {:multiple => true}, "music", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :dancing %>
	  			<%= form.check_box :category, {:multiple => true}, "dancing", nil %>
	  		</div>
	  		<div class="row">
	  		<%= form.label :rooftop %>
	  			<%= form.check_box :category, {:multiple => true}, "rooftop", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :relaxed %>
	  			<%= form.check_box :category, {:multiple => true}, "relaxed", nil %>
	  		</div>
	  	</div>
	  	<div class="col-md-4 border checklist">
	  		<div class="row">
	  			<h4>Restaurants</h4>
	  		</div>
	  		<div class="row">
	  			<%= form.label "Suit & Tie" %>
	  			<%= form.check_box :category, {:multiple => true}, "Suit & Tie", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label "Classy & Casual" %>
	  			<%= form.check_box :category, {:multiple => true}, "Classy & Casual", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label "Hipster & Biergartens" %>
	  			<%= form.check_box :category, {:multiple => true}, "Hipster & Biergartens", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :Quick_Bite %>
	  			<%= form.check_box :category, {:multiple => true}, "Quick Bite", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :Vegan %>
	  			<%= form.check_box :category, {:multiple => true}, "Vegan/Vegetarian", nil %>
	  		</div>
	  	</div>
	  	<div class="col-md-4 checklist">
	  		<div class="row">
	  			<h4>Activites</h4>
	  		</div>
	  		<div class="row">
	  			<%= form.label :athletic %>
	  			<%= form.check_box :category, {:multiple => true}, "Athletic", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :Relaxed_Fun %>
	  			<%= form.check_box :category, {:multiple => true}, "Relaxed Fun", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :Day_Trip %>
	  			<%= form.check_box :category, {:multiple => true}, "Day Trip", nil %>
	  		</div>
	  		<div class="row">
	  			<%= form.label :Free %>
	  			<%= form.check_box :category, {:multiple => true}, "Free", nil %>
	  		</div>
	  	</div>
	  </div>
	  <hr>
	  <div class="row checklist">
	  	<%= form.label :sponsor %>
	  	<%= form.check_box :sponsor %>
	  </div>
	  <hr>
	  <div class="actions row">
	    <%= form.submit %>
	  </div>
	<% end %>
</div>

app/views/venues/_form.html.erb
<%= form_with(model: venue, local: true) do |form| %>
  <% if venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :venue_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :venue_bio %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :venue_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :venue_phone %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :venue_image %>
  </div>

  <div class="field">
    <%= form.label :rating_id %>
    <%= form.number_field :rating_id, id: :venue_rating_id %>
  </div>

  <div class="field">
    <%= form.label :favorite_id %>
    <%= form.number_field :favorite_id, id: :venue_favorite_id %>
  </div>

  <div class="field">
    <%= form.label :bar %>
    <%= form.check_box :bar, id: :venue_bar %>
  </div>

  <div class="field">
    <%= form.label :restaurant %>
    <%= form.check_box :restaurant, id: :venue_restaurant %>
  </div>

  <div class="field">
    <%= form.label :activity %>
    <%= form.check_box :activity, id: :venue_activity %>
  </div>

  <div class="field">
    <%= form.label :sponsor %>
    <%= form.check_box :sponsor, id: :venue_sponsor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/venues/index.html.erb
<div class="row venueindex">
 <div class="row venuenav">
    <div class="col-md-4 active barnav bigbutton">
      <h3>Bar/Clubs</h3>
    </div>
    <div class="col-md-4 restnav bigbutton">
      <h3>Restaurants</h3>
    </div>
    <div class="col-md-4 actnav bigbutton">
      <h3>Activities</h3>
    </div>
  </div>

<!-- bars and clubs -->

  <div class="row" id="bars">
  <div class="col-md-2"></div>
    <div class="col-md-2">
        <h4 class="catbutton active" id= "music">Music</h4>
    </div>
    <div class="col-md-2">
        <h4 class="catbutton" id="dancing">Dancing</h4>
    </div>
    <div class="col-md-2">
        <h4 class="catbutton" id="rooftop">Rooftop</h4>
    </div>
    <div class="col-md-2">
        <h4 class="catbutton" id="relaxed">Relaxed</h4>
    </div>
    <div class="col-md-2"></div>
  </div>

<!-- restaurants -->

  <div class="row" id="restaurants">
    <div class="col-md-1"></div>
    <div class="col-md-2">
        <h4 class="catbutton" id="suit">Suit & Tie</h4>
    </div>
    <div class="col-md-2">
        <h4 class="catbutton" id="classy">Classy</h4>
    </div>
    <div class="col-md-2">
        <h4 class="catbutton" id="retro">Relaxed & Casual</h4>
    </div>
    <div class="col-md-2">
        <h4 class="catbutton" id="quick">Quick Bite</h4>
    </div>
    <div class="col-md-2">
        <h4 class="catbutton" id="vegan">Vegan/Vegetarian</h4>
    </div>
    <div class="col-md-1"></div>

  </div>

<!-- activities -->

  <div class="row" id="activities">
    <div class="col-md-2"></div>
    <div class="col-md-2">
        <h4 class="catbutton" id="athletic">Athletic</h4>
    </div>
    <div class="col-md-2">
        <h4 class="catbutton" id="relaxedfun">Relaxed fun</h4>
    </div>
    <div class="col-md-2">
        <h4 class="catbutton" id="day">Day trip</h4>
    </div>
    <div class="col-md-2">
        <h4 class="catbutton" id="free">Free</h4>
    </div>
    <div class="col-md-2"></div>
  </div>

    <div class="col-md-12-fluid changeview">
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 ">
           <div class="row">
             <h4 class="link" id="openmapview">Go to map view</h4>
             <h4 class="link" id="openlistview">Go to list view</h4>
           </div>
        </div>
          <div class="col-md-3"></div>
      </div>
    </div>
  <div class="map">
  </div>

<!-- venue list per category -->
  <div id="venues">
      <% @venues.each do |venue| %>

        <style>
          .venue-<%= venue.id %> { background-image: url(<%= venue.image %>); }
        </style>

        <div class="eachvenue">
        <div class="row">
            <div class="col-md-6 padding">
              <%= link_to venue do %>
                <article class=" image venue-<%=venue.id%>"></article>
              <% end %>
            </div>

            <div class="col-md-6 padding info">
              <div class="row">
                <h3><%=venue.name %></h3>
              </div>
              <div class="row">
               <p><%=venue.address %></p>
              </div>
              <div class="row">
               <p><%=venue.phone %></p>
              </div>
              <div class="row venuerating">
                <p class="ratetitle">DateNight:</p>
                <span style="width:<%= 23 * venue.mean_rating %>px" id="stars"></span>
              </div>
              <div class="row venuerating">
                <p class="ratetitle">Yelp:</p>
                <span style="width:<%= 23 * venue.google_rating%>px" id="stars"></span>
              </div>
              <div class="row venuerating">
                <p class="ratetitle">Google:</p>
                <span style="width:<%= 23 * venue.yelp_rating %>px" id="stars"></span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
</div>
<% case params[:page]
  when "restcat" then %>
    <script type="text/javascript">
        window.onload = function () {
          updateVenues(8);
          document.querySelector( '.restnav' ).click();
          document.querySelector( '#suit' ).click();
        };
    </script>
  <% when "actcat" then %>
    <script type="text/javascript">
      window.onload = function () {
        updateVenues(13);
        document.querySelector( '.actnav' ).click();
        document.querySelector( '#athletic' ).click();
      };
    </script>
  <% else %>
    <script type="text/javascript">
      updateVenues(4);
    </script>
  <% end %>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["google_key"] %>"></script>

app/views/venues/show.html.erb
 <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["google_key"] %>&libraries=places"></script>
 
<div class="row showvenue">
  <div class="col-md-12">
    <div class="row showinfo">
      <div class="col-md-6">
         <%= image_tag ( "#{@venue.image}" ) %>
      </div>
      <div class="col-md-5">
        <div class="row">
          <% if user_signed_in? %>
            <%= link_to favorites_path(@venue), method: :post, :class => "linkfav" do  image_tag 'addfav.png', :class => 'addfav'
             end %>
          <% end %>
          <h2><strong><em><%= @venue.name %></em></strong></h2>
        </div>
        <div class="row">
          <p><%= @venue.address %></p>
          <p><%= @venue.phone %></p>
        </div>
        <div class="row desc">
          <p><%= @venue.bio %></p>
        </div>
        <div class="row venuerating">
          <p class="ratetitle">DateNight:</p>
          <span style="width:<%= 23 * @venue.mean_rating %>px" id="stars"></span>
        </div>
        <div class="row venuerating">
          <p class="ratetitle">Yelp:</p>
          <span style="width:<%= 23 * (@venue.google_rating || 0)%>px" id="stars"></span>
        </div>
        <div class="row venuerating">
          <p class="ratetitle">Google:</p>
          <span style="width:<%= 23 * (@venue.yelp_rating || 0)%>px" id="stars"></span>
        </div>
      </div>
      <div class="col-md-1"></div>
    </div>
    <div class="row links">
      <div class="col-md-12">
        <%= link_to 'Edit', '#', :class => 'editvenuebutton' %> |
        <%= link_to 'Back', venues_path %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-7">
        <div class="row" id="map"></div>
      </div>

      <!-- reviews -->

      <div class="col-md-5">
        <div class="row reviews">
          <div class="row">
            <%= link_to posts_path do %>
              <h2>Reviews</h2>
            <% end %>
          </div>

          <div class="row newreview">
            <% if user_signed_in? %>
              <h4>New Review</h4>
              <div class="row">
                <div class="col-md-7">
                  <%= form_for :post, url: posts_path do |form| %>
                    <% if @post && @post.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
                        <ul>
                        <% @post.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                    <div class=" row field">
                      <%= form.label "Title: " %>
                      <%= form.text_field :post_name, :placeholder => 'Title', :class => " postinput", :id => "editpostname"  %>
                    </div>

                    <div class=" row field">
                      <%= form.label "Content: " %>
                      <%= form.text_area :text, :placeholder => 'Your post content', :class => " postinput", :id => "editposttext"  %>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="row field">
                      <%= form.label "Image: " %>
                      <%= form.file_field :image, :class => " postinput", id: "editpostimage"  %>
                    </div>

                    <div class="row actions">
                      <%= form.submit %>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>




          <div class="row">
            <% @venue.posts.each do |post| %>
              <div class="row posts">
                <div class="col-md-4">
                  <% if !post.image.blank? then postsrc = post.image else postsrc = post.venue.image end %>
                  <%= image_tag ( postsrc ) %>
                </div>
                <div class="col-md-8">
                  <div class="row">
                    <strong><%= link_to post do post.post_name  end %></strong>
                  </div>
                  <div class="row">
                   <%= link_to post.venue do post.venue.name  end %>
                  </div>
                  <div class="row">
                    <p><%= post.text %></p>
                  </div>
                  <div class="row">
                    <div class="col-md-4"></div>
                    <div class="col-md-8">
                      <p><%= distance_of_time_in_words(Time.now, post.created_at , options = {}) + " ago"%></p>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <%= render '/venues/editform' %>
    </div>
    <script>
        var editvenuebutton = document.querySelector( '.editvenuebutton' )
        var editvenue = document.querySelector( '.editvenue' )
        var close4 = document.getElementById( 'close4' )

        if( editvenuebutton )
          editvenuebutton.addEventListener('click', function(event){
              console.log(event);
              var editName = document.querySelector('#editname');
              var editPhone = document.querySelector('#editphone');
              var editRating = document.querySelector('#editrating');
              var editAddress = document.querySelector('#editaddress');
              var editImage = document.querySelector('.editimage')

              editvenue.style.display = 'inline-block';
              editName.value = "<%= @venue.name %>";
              editPhone.value = "<%= @venue.phone %>";
              editRating.value = <%= @venue.mean_rating %>;
              editAddress.value = "<%= @venue.address %>";
          });

        if( close4 )
        close4.addEventListener('click', function(event) {
            console.log(event);
            editvenue.style.display = 'none';
        });

      
        var map;

        function initialize() {
          // Create a map centered in Pyrmont, Sydney (Australia).
          map = new google.maps.Map(document.getElementById('map'), {
            center: {lat:<%= @venue.latitude %>, lng:<%= @venue.longitude %>},
            zoom: 15
          });

          // Search for Google's office in Australia.
          var request = {
            location: map.getCenter(),
            radius: '500',
            query: '<%= @venue.name %>'
          };

          var service = new google.maps.places.PlacesService(map);
          service.textSearch(request, callback);
        }
          var transitLayer = new google.maps.TransitLayer();
             transitLayer.setMap(map);
        // Checks that the PlacesServiceStatus is OK, and adds a marker
        // using the place ID and location from the PlacesService.
        function callback(results, status) {
          if (status == google.maps.places.PlacesServiceStatus.OK) {
            var marker = new google.maps.Marker({
              map: map,
              place: {
                placeId: results[0].place_id,
                location: results[0].geometry.location
              }
            });
          }
        }

        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </div>
</div>