config/routes.rb
Rails.application.routes.draw do
  resources :venuecategories
  resources :categories
  root to: "home#index"
  resources :favorites
  resources :ratings
  resources :comments
  resources :posts
  resources :profile
  get '/venues/map_all' => 'venues#map_all', as: :venue_map_all
  get '/venues(/type/:page)' => 'venues#index', as: :venues_page
  resources :venues
  get 'categories/:category_id/venues' => 'venues#category_feed', as: :venue_category_feed
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  get '/map' => 'map#index'  
  post '/posts/:id'=> 'posts#update', as: :post_id
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'venues/:venue_id/star/:rating' => 'ratings#update', as: :venue_rating
  get 'showvenue' => 'venues#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :venue_categories
	has_many :venues, :through => :venue_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :venue
  belongs_to :location, required: false
  belongs_to :post, required: false
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :venue
  mount_uploader :image, ImageUploader
  has_many :comments
  has_many :favorites
  has_many :ratings
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :venue, required: false
  belongs_to :post, required: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_many :ratings
  has_many :favorites
  has_many :venues, :through => :favorites
  has_many :posts
  has_many :comments
end

app/models/venue.rb
class Venue < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :venue_categories
	has_many :categories, :through => :venue_categories
	has_many :ratings
	has_many :favorites
	has_many :users , :through => :favorites
	has_many :posts

	def mean_rating
    self.ratings.average(:rating).to_f
  end
  geocoded_by :address
	after_validation :geocode
end

app/models/venue_category.rb
class VenueCategory < ApplicationRecord
  belongs_to :venue
  belongs_to :category
end

app/controllers/map_controller.rb
class MapController < ApplicationController
	def index
		@venues = Venue.all
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-4">
				<%= link_to root_path do %>
					<h5>Home</h5>
				<% end %>
				<%= link_to venues_path do %>
					<h5>All Venues</h5>
				<% end %>
				<%= link_to posts_path do %>
					<h5>Forum</h5>
				<% end %>
			</div>
			<div class="col-md-4">
			</div>
			<div class="col-md-4">
				<h5>© 2017 Date Night</h5>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="container-fluid">
		<div class="tint">
		<nav class="row">
			<div id="links" class="col-md-12">
				<div id="otherlinks">
					<% if user_signed_in? && current_user.admin? %>
						<%= link_to new_venue_path do %>
							<h4>New Venue</h4>
						<% end %>
					<% end %>
					<% if user_signed_in? %>
	  						<%= link_to "Sign Out", destroy_user_session_path, method: :delete, :id => 'signout' %>
	  					<% else %>
	         	<%= link_to 'Sign Up', '#', :id => 'signup' %>
		 				<%= link_to 'Sign In', '#', :id => 'signin' %>
	 				<% end %>
	 			</div>
 				<div id="imglinks">
					<%= link_to venues_path do %>
						<%= image_tag "search.png" %>
					<% end %>
					<%= link_to profile_index_path do %>
						<%= image_tag "profile.png" %>
					<% end %>
				</div>
 			</div>
		</nav>	
		<div class="row">
			<div class="col-md-12 heading">
				<%= link_to '/' do "Rondivu" end %>
       	<p class="notice"><%= notice %></p>
      	<p class="alert"><%= alert %></p>
 			</div>
		</div>
		<% if @homepage %>
			<div class="row index">
				<div class="row">
					<h2>First Choose the Type of Date to Browse</h2>
					<div class="col-md-4 bars">
						<div class="row">
							<h5>Fun night out listening to music, dancing, or at a lounge to mingle?</h5>
						</div>
						<div class="row">
							<%= link_to venues_path, :id => "barcat" do %>
								<h2>Bars/Clubs</h2>
							<% end %>
						</div>
					</div>
					<div class="col-md-4 restaurants">
						<div class="row">
							<h5>Looking for a good vibe? Or do you want to dress up and treat them to a special night.</h5>
						</div>
						<div class="row">
							<%= link_to venues_page_path(:restcat), :id => "restcat" do %>
								<h2>Restaurants</h2>
							<% end %>
						</div>
					</div>
					<div class="col-md-4 activities">
						<div class="row">
							<h5>Tired of the average date? Let's take a jump and do something new!</h5>
						</div>
						<div class="row">
							<%= link_to venues_page_path(:actcat), :id => "actcat" do %>
								<h2>Activities</h2>
							<% end %>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<%= image_tag "arrow.png", :class => "arrow" %>
					</div>
				</div>
			</div>
			<style>
				body {
					padding-bottom: 0;
				}
				.index {
					padding: 0 0 5% 0;
				}
				header {
					position: relative;
					height: 95%;
					background-attachment: fixed;
					background-position: center;

				}
				header .heading a {
					font-size: 120px;
				}
				.arrow {
				  -moz-animation: bounce 2s infinite;
				  -webkit-animation: bounce 2s infinite;
				  animation: bounce 2s infinite;
				  height: 50px;
				}
				@keyframes bounce {
				  0%, 20%, 50%, 80%, 100% {
				    transform: translateY(0);
				  }
				  40% {
				    transform: translateY(-30px);
				  }
				  60% {
				    transform: translateY(-15px);
				  }
				}
				.eachvenue {
					background-image: none;
					background-color: rgba(216,185,153,1);
				}


			</style>
		<% end %>	
	</div>
</header>

app/views/layouts/_signin.html.erb
<div id="sibox">

	<h2>Sign In</h2>

	<div id="close">x</div>

	<%= form_for(:user, :url => new_user_session_path) do |f| %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.check_box :remember_me %>
    <%= f.label :remember_me %>
  </div>

  <div class="actions" id="signinsubmit">
      <%= f.submit "Log in", :class => "button" %>
  </div>

  <%= link_to "Forgot your password?", new_password_path(:user) %>

<% end %>

</div>

app/views/layouts/_signup.html.erb
<div id="subox">
	<h3>Sign Up</h3>
	<div id="close2">x</div>
	<%= form_for(:user, :url => user_registration_path) do |f| %>
   
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br>
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

  <div class="actions">
    <%= f.submit "Sign up", :class => "button"%>
  </div>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rondivu</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap-grid.css">
    <link href="https://fonts.googleapis.com/css?family=Mate+SC|Lusitana|Playfair+Display+SC|Prata|Oleo+Script|Lalezar|Merienda+One" rel="stylesheet">
  </head>

  <body>

  

 	<%= render '/layouts/header' %>
  
  <%= render '/layouts/signin' %>

  <%= render '/layouts/signup' %>

  <div class="container-fluid page">
   	<%= yield %>
  </div>

  <%= render '/layouts/footer' %>

  </body>
</html>